# Generated by Django 6.0.4 on 2026-05-01 22:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('computer_science', 'Computer Science'), ('engineering', 'Engineering'), ('business', 'Business'), ('social_behavioural', 'Social & Behavioural Science'), ('general', 'General / All Faculties')], default='general', max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('tip', models.TextField(blank=True, help_text='A short tip or what the interviewer is really looking for.')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags e.g. 'OOP, Python, algorithms'", max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within faculty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['faculty', 'order', 'difficulty'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('interviewer_email', models.EmailField(max_length=254)),
                ('interviewer_phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs/')),
                ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
