# Generated by Django 6.0.4 on 2026-05-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='faculty',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('engineering', 'Engineering'), ('business', 'Business'), ('social_behavioural', 'Social & Behavioural Science'), ('medicine', 'Medicine & Health Sciences'), ('law', 'Law'), ('arts', 'Arts & Humanities'), ('natural_sciences', 'Natural Sciences'), ('education', 'Education'), ('general', 'General / All Faculties')], default='general', max_length=50),
        ),
    ]
