# Generated by Django 6.0.4 on 2026-05-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_interviewquestion_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('computer_science', 'Computer Science'), ('engineering', 'Engineering'), ('business', 'Business'), ('social_behavioural', 'Social & Behavioural Science'), ('medicine', 'Medicine & Health Sciences'), ('law', 'Law'), ('arts', 'Arts & Humanities'), ('natural_sciences', 'Natural Sciences'), ('education', 'Education'), ('general', 'General / All Faculties')], max_length=50)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('tip', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('submitted_by_name', models.CharField(blank=True, max_length=255)),
                ('submitted_by_email', models.EmailField(blank=True, max_length=254)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
