# Generated by Django 6.0.4 on 2026-05-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_question_submissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['status', 'faculty', 'difficulty'], name='core_interv_status_4b8863_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['status', 'created_at'], name='core_interv_status_7d8c4e_idx'),
        ),
    ]
