# Generated by Django 6.0.4 on 2026-05-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVBuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('short_description', models.CharField(max_length=240)),
                ('link', models.URLField(max_length=500, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_by_name', models.CharField(blank=True, max_length=255)),
                ('submitted_by_email', models.EmailField(blank=True, max_length=254)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name', 'id'],
                'indexes': [models.Index(fields=['status', 'order', 'name'], name='core_cvbuil_status_4783c3_idx'), models.Index(fields=['status', 'created_at'], name='core_cvbuil_status_9de25a_idx')],
            },
        ),
    ]
